# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fe5d68c52803a44c73f9d49cecce3a4e2f959e5edcef834f9a60a8b6bd5d7bf972bec8729e84cfab6e8e50f32f4d0ce9fe066d94d8fc729831a8e0a4e4c65ce

test:
  secret_key_base: e23a4797e3107add1c97364b0fd4e700e97c86f4b1ccbe3ebff623cf4736090f8d63c4183652c209598a39895872e133246dccc70131075d64e35da9f4884d8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
